name: Publish

on:
  push:
    branches:
    - master

jobs:
  publish:
    steps:
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.7.1
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
